require 'locket.componentfactory'
require 'locket.component'

require 'locket.gameobject'

require 'locket.cpositionable'
require 'locket.crotatable'
require 'locket.calignable'
require 'locket.ccolorable'
require 'locket.cspriterenderer'
require 'locket.crendercircle'
require 'locket.cspinner'
require 'locket.cgravity'
require 'locket.crenderbox'
require 'locket.caaboundingbox'
require 'locket.cplatformcollision'
require 'locket.cplayercontroller'
